theme: jekyll-theme-minimal
#site data
title: Kalli DnD
description: [A place to find all the materials revelant to the kalli dnd world or possible future projects]
logo: [dndkalli.github.io/favicon.ico]
